Current_Position:
  Gpio:
  - 180
  - 180
  - 180
  - 0
  - 0
  - 0
  I2C:
  - 0
  - 30
  - 110
  - 0
  - 150
  - 150
  - 0
  - 180
  - 0
  - 60
  - 150
  - 0
  - 180
  - 180
  - 0
  - 90
DC_Motor:
  left:
    back: 20
    enable: 22
    front: 26
  right:
    back: 16
    enable: 27
    front: 19
Initial_Position:
  Gpio:
  - 180
  - 180
  - 180
  - 0
  - 0
  - 0
  I2C:
  - 0
  - 50
  - 130
  - 0
  - 170
  - 170
  - 0
  - 180
  - 0
  - 60
  - 150
  - 0
  - 180
  - 180
  - 0
  - 90
Pin:
  Gpio:
  - 12
  - 11
  - 8
  - 10
  - 9
  - 25
  I2C:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
Sensor:
  fire: 13
  gas: 4
  ldr: 21
  mpu6050: I2C
  smoke: 7
  status: 'on'
  ultrasonic:
    echo: 11
    trigger: 8


